### PR TITLE
Feature/messaging type

### LINKED ISSUE #185: Support for 2.2 breaking change `messaging_type`
Following on from Facebooks announcement on last week, there has been a breaking change introduced to version 2.2 of the messenger send API (full details at https://developers.facebook.com/docs/messenger-platform/reference/send-api/)

We need to add a message type to all send requests. Any send requests sent after May 7, 2018 without this property will be rejected, so It's pretty important to get it in.

I'm going to look at adding this in in the next week or so. Will issue a pull request when It's done.

### PR DESCRIPTION
**Pull request by abury**
Fixes #185 
Adds support for the `message_type`attribute required in Messenger 2.2

### CODE REVIEW

**Comment by jgorset** [comment]
Great, thank you! :sparkles: :cake: :sparkles:

**Comment by ylecuyer** [comment]
@jgorset I don't understand why you prevented my PR to be merged because of rubocop errors but did let this one get merged with errors ? Now the build of my PR fail because of this one

**Comment by jgorset** [comment]
Sorry about that, @ylecuyer – I rushed it and fucked up.

**Comment by abury** [comment]
Sorry guys, didn’t mean to break anything. Everything passed so I didn’t realise my quotation marks had broken anything. ☹️

**Comment by jgorset** [comment]
Not a problem @abury! :)

**Pull request merged**
