### PR TITLE
Implement ServerNoError

### LINKED ISSUE #113: Custom server class for development
For development purpose I use the following server class:

```ruby
class ServerNoError < Facebook::Messenger::Server

  def call(env)
    begin
      super
    rescue Exception => e

        send("\xF0\x9F\x98\xB1")  #😱
        send(e.inspect)
        send(e.backtrace.join("\n")[0..636] + "...")

        @response.status = 200
        @response.finish

    end
  end

  private

  def send(text)
    
     sender_id = parsed_body["entry"][0]["messaging"][0]["sender"]["id"]

      Bot.deliver({
        recipient: {
          id: sender_id
        },
        message: {
          text: text
        }
      }, access_token: ENV['ACCESS_TOKEN'])
  end

end

run ServerNoError
```

Because when there is an error in the message handling, the messenger platform keep sending the message until the response code changes to 200.
Moreover, you have to read the log in order to find the corresponding stacktrace.

When there is a lot of 500 errors the messenger platform seems to stall the incoming messages.

Preview

Maybe this can be integrated as an option?

### PR DESCRIPTION
**Pull request by ylecuyer**
Fix #113

### CODE REVIEW

**Comment by jgorset** [comment]
Neat, thanks! Rubocop is mad, though – I'll try to take a look at it this weekend unless you beat me to it.

**Comment by ylecuyer** [comment]
I'll try to fix 2 of them but there is one I'll have to add a local exception:

```
Offenses:

**This one will be fixed**

lib/facebook/messenger/server_no_error.rb:5:5: C: Missing top-level class documentation comment.
    class ServerNoError < Server
    ^^^^^

**I'll have to add a rubocop local exception for this one because it is the heart of the no exception server**

lib/facebook/messenger/server_no_error.rb:8:7: W: Avoid rescuing the Exception class. Perhaps you meant to rescue StandardError?
      rescue Exception => e ...
      ^^^^^^^^^^^^^^^^^^^^^

**This one will be fixed**

lib/facebook/messenger/server_no_error.rb:9:36: C: Use only ascii symbols in comments.
        send("\xF0\x9F\x98\xB1") # 😱
                                   ^
```

**Comment by ylecuyer** [comment]
#191 needs to be merged first to have the build to pass

**Comment by jgorset** [comment]
:sparkles: :cake: ✨

**Pull request merged**
