### PR TITLE
Added `reaction` event

### PR DESCRIPTION
**Pull request by denmarkmeralpis**
## Usage

```ruby
Bot.on :reaction do |message|
  message.emoji # => "👍"
  message.action # => "react"
  message.reaction # => "like"

  message.reply(text: 'Thanks for liking my message!')
end
```

### CODE REVIEW

**Comment by amrutjadhav** [comment]
This is nice! 👍

**Comment by jgorset** [comment]
Sweet, with tests and examples and all! Thanks for the great pull request @denmarkmeralpis!

**Comment by jgorset** [comment]
I released 1.5.0, and it has this in it!

**Comment by denmarkmeralpis** [comment]
Yey! Thanks 🤘🏻

**Pull request merged**
