### PR TITLE
Add ad_id field to referral nested class

### PR DESCRIPTION
**Pull request by diego-suarez**
I just added the following to the class Facebook::Messenger::Incoming::Referral::Referral:

```
          def ad_id
            @referral['ad_id'] if @referral.key?('ad_id')
          end
```

Is to have access to the ad_id when the ad_source is ADS

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks @diego-suarez! :cake: In the future, it's good to include a test if the repository you're contributing to has a test suite. I [made one](https://github.com/jgorset/facebook-messenger/commit/f344feca3e889acbfaf40a1c4cf0c7de598d78d3) for this and merged it.

**Comment by diego-suarez** [comment]
Thanks sr! I'm sorry for the test suite.. next time it will be included for sure!

**Comment by akichim21** [comment]
hi.
Have not you delivered yet?
I would like to use this method.

**Comment by diego-suarez** [comment]
@akichim21 Yes, it was merged to master, but was not published on a release yet. Meanwhile you can use it if you point to the master branch on your project.

**Pull request merged**
